CREATE OR REPLACE VIEW KOCURY_PER OF KOCURY_O
WITH OBJECT IDENTIFIER (PSEUDO) AS
  SELECT
    imie,
    plec,
    pseudo,
    funkcja,
    szef,
    w_stadku_od,
    przydzial_myszy,
    myszy_extra,
    nr_bandy
FROM KOCURY;

CREATE OR REPLACE VIEW PLEBS_PER OF PLEBS
WITH OBJECT IDENTIFIER (NR_PLEBS) AS
  SELECT NR_PLEBS, MAKE_REF(KOCURY_PER, PSEUDO) PSEUDO
  FROM PLEBS_REL;

CREATE OR REPLACE VIEW ELITA_PER OF ELITA
WITH OBJECT IDENTIFIER (NR_ELITA) AS
  SELECT NR_ELITA, MAKE_REF(KOCURY_PER, PSEUDO) PSEUDO, MAKE_REF(PLEBS_PER, SLUGA_NR) SLUGA
  FROM ELITA_REL;

CREATE OR REPLACE VIEW KONTO_PER OF KONTO
WITH OBJECT IDENTIFIER (NR) AS
  SELECT NR, MAKE_REF(ELITA_PER, WLASCICIEL_NR) WLASCICIEL, DATA_WPROWADZANIA, DATA_USUNIECIA
  FROM KONTO_REL;

CREATE OR REPLACE VIEW WROGOWIE_KOC_PER OF WROGOWIE_KOCUROW_O
WITH OBJECT IDENTIFIER (NR_INCYDENTU) AS
  SELECT ROWNUM NR_INCYDENTU, MAKE_REF(KOCURY_PER, PSEUDO) PSEUDO, IMIE_WROGA, DATA_INCYDENTU, OPIS_INCYDENTU
  FROM WROGOWIE_KOCUROW;

-- Widok, który wybiera szefa + widok, który wybiera wszystko oprócz szefa i połączyć referencją
-- wtedy widok nie jest połączony sam ze sobą
-- DRUGI OBIEKT WIERSZOWY