--REFERENCJE
SELECT ER.KOT.PSEUDO "CZLONEK ELITY",
  ER.KOT.CALK_PRZYDZIAL_MYSZY() "ILE MYSZY POŻERA",
  ER.SLUGA.KOT.PSEUDO "SLUGA"
FROM ELITA_test_PER ER;

--PODZAPYTANIE
SELECT
  KP.WLASCICIEL.KOT.PSEUDO "PAN I WLADCA",
  KP.DATA_WPROWADZENIA "KIEDY DOSTAŁ"
  FROM KONTO_test_PER KP
WHERE KP.CZY_USUNIETE() = 0 AND
      KP.WLASCICIEL.SLUGA.KOT.PSEUDO IN
      (SELECT PP.KOT.PSEUDO
        FROM PLEBS_test_PER PP
        WHERE PP.KOT.NR_BANDY = 3);

--GROUP BY
SELECT
  KP.WLASCICIEL.KOT.PSEUDO "PAN I WLADCA",
  COUNT(*) "MA NA KONCIE"
  FROM KONTO_test_PER KP
WHERE KP.CZY_USUNIETE() = 0
GROUP BY KP.WLASCICIEL.KOT.PSEUDO;

-- LISTA 2
-- ZAD 18
SELECT KP.IMIE, KP.W_STADKU_OD "POLUJE OD"
FROM KOCURY_test_PER KP
WHERE KP.POROWNAJ_DATY_WSTAP('JACEK') < 0
ORDER BY KP.W_STADKU_OD DESC;

-- ZAD 22

SELECT MIN(WK.KOT.FUNKCJA), WK.KOT.PSEUDO "PSEUDONIM KOTA", COUNT(*)
FROM WROGOWIE_KOC_test_PER WK
GROUP BY WK.KOT.PSEUDO
HAVING COUNT(*) > 1;

--LISTA 3
--zad 37

DECLARE
  CURSOR KURSOR IS
    SELECT ROWNUM, PSEUDO, SUMA
    FROM
      (SELECT
      PSEUDO,
      KT.CALK_PRZYDZIAL_MYSZY() SUMA
      FROM KOCURY_test_PER KT
      ORDER BY SUMA DESC);

BEGIN
  DBMS_OUTPUT.PUT_LINE('NR' || '   ' || 'PSEUDONIM' || '   ' || 'ZJADA' );

  FOR KOT IN KURSOR
  LOOP
    EXIT WHEN KOT.ROWNUM > 5;
    DBMS_OUTPUT.PUT_LINE(KOT.ROWNUM || '    ' || KOT.PSEUDO || '    ' || KOT.SUMA);
  END LOOP;
END;

--36
DECLARE
  PSEUDO_KOTA VARCHAR2(15);
  KOT KOCURY_test_O;

BEGIN
  PSEUDO_KOTA := :X;

  SELECT VALUE(KT)
  INTO KOT
    FROM KOCURY_test_PER KT
  WHERE PSEUDO = PSEUDO_KOTA;

  IF KOT.CALK_PRZYDZIAL_MYSZY() * 12 > 700 THEN
    DBMS_OUTPUT.PUT_LINE(KOT.IMIE || ' CALKOWITY ROCZNY PRZYDZIAL MYSZY > 700');
  END IF;

  IF KOT.CZY_ZAWIERA('A') = 1 THEN
    DBMS_OUTPUT.PUT_LINE(KOT.IMIE || ' IMIE ZAWIERA LITERE A');
  END IF;

  IF KOT.MIESIAC_PRZYSTAPIENIA() = 1 THEN
    DBMS_OUTPUT.PUT_LINE(KOT.IMIE || ' STYCZEN JEST MIESIĄCEM PRZYSTAPIENIA DO STADA');
  END IF;

  IF
    KOT.CALK_PRZYDZIAL_MYSZY() * 12 * 12 <= 700
    AND
     KOT.CZY_ZAWIERA('A') = 0
    AND
    KOT.MIESIAC_PRZYSTAPIENIA() != 1
  THEN
    DBMS_OUTPUT.PUT_LINE(KOT.IMIE || ' NIE ODPOWIADA KRYTERIOM');
  END IF;

END;