CREATE OR REPLACE TYPE KOCURY_48 AS OBJECT
(IMIE            VARCHAR2(15),
 PLEC            VARCHAR2(1),
 PSEUDO          VARCHAR2(15),
 FUNKCJA         VARCHAR2(10),
 SZEF            VARCHAR2(15),
 W_STADKU_OD     DATE,
 PRZYDZIAL_MYSZY NUMBER(3),
 MYSZY_EXTRA     NUMBER(3),
 NR_BANDY        NUMBER(2),
MAP MEMBER FUNCTION POROWNAJ RETURN VARCHAR2,
MEMBER FUNCTION CALK_PRZYDZIAL_MYSZY RETURN NUMBER,
MEMBER FUNCTION POROWNAJ_DATY_WSTAP(KOT VARCHAR2) RETURN NUMBER,
MEMBER FUNCTION CZY_ZAWIERA(LITERA VARCHAR2) RETURN NUMBER,
MEMBER FUNCTION MIESIAC_PRZYSTAPIENIA RETURN NUMBER
);

CREATE OR REPLACE TYPE BODY KOCURY_48 AS
  MAP MEMBER FUNCTION POROWNAJ RETURN VARCHAR2 IS
    BEGIN
      RETURN PSEUDO;
    END;

  MEMBER FUNCTION CZY_ZAWIERA(LITERA VARCHAR2) RETURN NUMBER IS
    BEGIN
      IF INSTR(SELF.IMIE, LITERA) > 0 THEN
        RETURN 1;
      ELSE
        RETURN 0;
      END IF;
    END;

  MEMBER FUNCTION MIESIAC_PRZYSTAPIENIA RETURN NUMBER IS
    BEGIN
      RETURN EXTRACT(MONTH FROM SELF.W_STADKU_OD);
    END;

  MEMBER FUNCTION CALK_PRZYDZIAL_MYSZY RETURN NUMBER IS
    BEGIN
      RETURN NVL(PRZYDZIAL_MYSZY,0) + NVL(MYSZY_EXTRA,0);
    END;

  MEMBER FUNCTION POROWNAJ_DATY_WSTAP(KOT VARCHAR2) RETURN NUMBER IS
    INNY_KOT KOCURY%ROWTYPE;
    BEGIN
      SELECT *
        INTO INNY_KOT
      FROM KOCURY
      WHERE IMIE = KOT;

      IF SELF.W_STADKU_OD < INNY_KOT.W_STADKU_OD THEN
        RETURN -1;

      ELSIF SELF.W_STADKU_OD = INNY_KOT.W_STADKU_OD THEN
        RETURN 0;

      ELSE
        RETURN 1;
      END IF;

    END;
  END;

