--ZAD 40
-- Przerobić blok z zadania 39 na procedurę umieszczoną w bazie danych

CREATE OR REPLACE PROCEDURE DodajBande
  (NRB IN KOCURY.NR_BANDY%TYPE,
  NAZWAB IN BANDY.NAZWA%TYPE,
  TERENB IN BANDY.TEREN%TYPE )

IS

  ILE_NR NUMBER;
  ILE_NAZWA NUMBER;
  ILE_TEREN NUMBER;
  ZLY_NUMER EXCEPTION;
  ZNALEZIONO EXCEPTION;
  INFO VARCHAR2(50) := ' ';

BEGIN
  IF NRB <= 0 THEN
    RAISE ZLY_NUMER;
  END IF;

  SELECT COUNT(*)
  INTO ILE_NR
  FROM BANDY
  WHERE NR_BANDY = NRB;

  SELECT COUNT(*)
  INTO ILE_NAZWA
  FROM BANDY
  WHERE NAZWA = NAZWAB;

  SELECT COUNT(*)
  INTO ILE_TEREN
  FROM BANDY
  WHERE TEREN = TERENB;

  IF ILE_NR = 0 AND ILE_NAZWA = 0 AND ILE_TEREN = 0 THEN
     INSERT INTO BANDY
      (NR_BANDY, NAZWA , TEREN)
    VALUES
      (NRB, NAZWAB, TERENB);
  ELSE
     IF ILE_NR > 0 THEN INFO := INFO || NRB || ' ';
       END IF;
     IF ILE_NAZWA > 0 THEN  INFO := INFO || NAZWAB || ' ';
        END IF;
    IF ILE_TEREN > 0 THEN INFO := INFO || TERENB || ' ';
      END IF;
    RAISE ZNALEZIONO;
  END IF;

  EXCEPTION
    WHEN ZLY_NUMER
      THEN DBMS_OUTPUT.PUT_LINE('PODANO NIEODPOWIEDNI NUMER BANDY');
    WHEN ZNALEZIONO
      THEN DBMS_OUTPUT.PUT_LINE(INFO || ' JUZ ISTNIEJE');

END;

CALL DODAJBANDE(6, 'DZIEWCZYNKI', 'MIASTO' );
SELECT * FROM BANDY;
ROLLBACK;