CREATE OR REPLACE PACKAGE PAKIET44 AS
  FUNCTION ObliczPodatek(PSEUDONIM KOCURY.PSEUDO%TYPE) RETURN NUMBER;
  PROCEDURE DodajBande(NRB IN KOCURY.NR_BANDY%TYPE,
  NAZWAB IN BANDY.NAZWA%TYPE,
  TERENB IN BANDY.TEREN%TYPE );
END PAKIET44;

CREATE OR REPLACE PACKAGE BODY PAKIET44 AS

  FUNCTION ObliczPodatek
  (PSEUDONIM KOCURY.PSEUDO%TYPE)
  RETURN NUMBER
  AS
  PODATEK NUMBER := 0;
  PRZYDZIAL KOCURY.PRZYDZIAL_MYSZY%TYPE;
  EXTRA KOCURY.MYSZY_EXTRA%TYPE;
  ILE_PODWLAD NUMBER;
  ILE_WROGOW NUMBER;

BEGIN
  SELECT NVL(PRZYDZIAL_MYSZY,0), NVL(MYSZY_EXTRA,0)
  INTO PRZYDZIAL, EXTRA
  FROM KOCURY
  WHERE PSEUDO = PSEUDONIM;

  SELECT COUNT(PSEUDO)
  INTO ILE_PODWLAD
  FROM KOCURY
  WHERE SZEF = PSEUDONIM;

  SELECT COUNT(IMIE_WROGA)
  INTO ILE_WROGOW
  FROM WROGOWIE_KOCUROW
  WHERE PSEUDO = PSEUDONIM;

--   PODATEK KAZDEGO KOTA
  PODATEK := PODATEK + CEIL(0.05 * PRZYDZIAL);

--   GDY KOT NIE MA PODWLADNYCH
  IF ILE_PODWLAD = 0 THEN
    PODATEK := PODATEK + 2;
  END IF;

--   GDY KOT NIE MA WROGOW
  IF ILE_WROGOW = 0 THEN
    PODATEK := PODATEK + 1;
  END IF;

--   GDY KOT NIE MA MYSZY EXTRA, BO MOŻE JEST ZBYT LENIWY ŻEBY SIĘ O NIE STARAĆ
  IF EXTRA = 0 THEN
    PODATEK := PODATEK +1;
  END IF;

  RETURN PODATEK;
END ObliczPodatek;

PROCEDURE DodajBande
  (NRB IN KOCURY.NR_BANDY%TYPE,
  NAZWAB IN BANDY.NAZWA%TYPE,
  TERENB IN BANDY.TEREN%TYPE )
IS
  ILE_NR NUMBER;
  ILE_NAZWA NUMBER;
  ILE_TEREN NUMBER;
  ZLY_NUMER EXCEPTION;
  ZNALEZIONO EXCEPTION;
  INFO VARCHAR2(50) := ' ';

BEGIN
  IF NRB <= 0 THEN
    RAISE ZLY_NUMER;
  END IF;

  SELECT COUNT(*)
  INTO ILE_NR
  FROM BANDY
  WHERE NR_BANDY = NRB;

  SELECT COUNT(*)
  INTO ILE_NAZWA
  FROM BANDY
  WHERE NAZWA = NAZWAB;

  SELECT COUNT(*)
  INTO ILE_TEREN
  FROM BANDY
  WHERE TEREN = TERENB;

  IF ILE_NR = 0 AND ILE_NAZWA = 0 AND ILE_TEREN = 0 THEN
     INSERT INTO BANDY
      (NR_BANDY, NAZWA , TEREN)
    VALUES
      (NRB, NAZWAB, TERENB);
  ELSE
     IF ILE_NR > 0 THEN INFO := INFO || NRB || ' ';
       END IF;
     IF ILE_NAZWA > 0 THEN  INFO := INFO || NAZWAB || ' ';
        END IF;
    IF ILE_TEREN > 0 THEN INFO := INFO || TERENB || ' ';
      END IF;
    RAISE ZNALEZIONO;
  END IF;

  EXCEPTION
    WHEN ZLY_NUMER
      THEN DBMS_OUTPUT.PUT_LINE('PODANO NIEODPOWIEDNI NUMER BANDY');
    WHEN ZNALEZIONO
      THEN DBMS_OUTPUT.PUT_LINE(INFO || ' JUZ ISTNIEJE');

END DodajBande;
END PAKIET44;

SELECT PSEUDO "PODATNIK", PAKIET44.ObliczPodatek (PSEUDO) "PODATEK"
FROM KOCURY;