DECLARE
  POLECENIE_CREATE VARCHAR2(3000);
BEGIN
  POLECENIE_CREATE := 'CREATE TABLE MYSZY(
      NR_MYSZY NUMBER(10) CONSTRAINT my_nr_pk PRIMARY KEY,
      LOWCA VARCHAR2(15) CONSTRAINT my_lo_fk REFERENCES Kocury(PSEUDO),
      ZJADACZ VARCHAR2(15) CONSTRAINT my_zj_fk REFERENCES Kocury(PSEUDO),
      WAGA_MYSZY NUMBER(2) CONSTRAINT my_wa_ck CHECK (WAGA_MYSZY BETWEEN 15 AND 25),
      DATA_ZLOWIENIA DATE,
      DATA_WYDANIA DATE )';

  EXECUTE IMMEDIATE POLECENIE_CREATE;
END;