--Tworzenie prywatnych kocich kont

DECLARE
  CREATE_KONTO VARCHAR2(1000);
BEGIN
  FOR KOT IN (SELECT PSEUDO FROM KOCURY)
    LOOP
    CREATE_KONTO := 'CREATE TABLE KONTO_' || KOT.PSEUDO || '(
      NR_MYSZY NUMBER(10) CONSTRAINT my_' || KOT.PSEUDO || '_pk PRIMARY KEY,
      WAGA_MYSZY NUMBER(2) CONSTRAINT my_' || KOT.PSEUDO || '_ck CHECK (WAGA_MYSZY BETWEEN 15 AND 25),
      DATA_ZLOWIENIA DATE CONSTRAINT my_' || KOT.PSEUDO || '_nn NOT NULL)';
    EXECUTE IMMEDIATE CREATE_KONTO;
  END LOOP;
END;

-- Usuwanie kont

DECLARE
  DROP_KONTO VARCHAR2(1000);
BEGIN
  FOR KOT IN (SELECT PSEUDO FROM KOCURY)
    LOOP
    DROP_KONTO := 'DROP TABLE KONTO_' || KOT.PSEUDO;

    EXECUTE IMMEDIATE DROP_KONTO;
  END LOOP;
END;