CREATE OR REPLACE PROCEDURE PRZYJMIJ_MYSZY (PSEUDO KOCURY.PSEUDO%TYPE) AS
  TYPE REK IS RECORD (NR MYSZY.NR_MYSZY%TYPE, WM MYSZY.WAGA_MYSZY%TYPE, DZ MYSZY.DATA_ZLOWIENIA%TYPE);
  TYPE TMP IS TABLE OF REK;
  ZLAPANE TMP;

  ILE_KOTOW NUMBER;
  ZLE_PSEUDO EXCEPTION;

BEGIN

  SELECT COUNT(*)
    INTO ILE_KOTOW
    FROM KOCURY K
      WHERE K.PSEUDO = PSEUDO;

  IF ILE_KOTOW = 0 THEN
    RAISE ZLE_PSEUDO;
  END IF;

  EXECUTE IMMEDIATE  'SELECT * FROM KONTO_' || PSEUDO || ''
  BULK COLLECT INTO ZLAPANE;

  FORALL IND IN 1..ZLAPANE.LAST
  INSERT INTO MYSZY VALUES (ZLAPANE(IND).NR , PSEUDO, NULL, ZLAPANE(IND).WM, ZLAPANE(IND).DZ, NULL);


  EXECUTE IMMEDIATE 'DELETE FROM KONTO_' || PSEUDO || '';
  COMMIT;

  EXCEPTION
    WHEN ZLE_PSEUDO THEN
      DBMS_OUTPUT.PUT_LINE('Nie istnieje kot o takim pseudonimie: ' || PSEUDO);
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLERRM);

END;



INSERT INTO KONTO_TYGRYS VALUES(1,20,SYSDATE);
INSERT INTO KONTO_TYGRYS VALUES(2,16,SYSDATE);
INSERT INTO KONTO_TYGRYS VALUES(3,19,SYSDATE);

CALL PRZYJMIJ_MYSZY('TYGRYS');
COMMIT;
ROLLBACK;